# Generated by Django 3.1.8 on 2022-12-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBI', '0004_auto_20221202_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='contact',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='designation',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='empcode',
            new_name='Mobile_Number',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='empdept',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='joiningdate',
        ),
    ]
