# Generated by Django 3.1.8 on 2022-12-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBI', '0006_auto_20221202_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
