# Generated by Django 3.1.8 on 2022-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBI', '0011_auto_20221202_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='balance',
            field=models.CharField(max_length=100),
        ),
    ]
