# Generated by Django 4.1.3 on 2022-12-03 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SBI', '0015_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='Loan_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
